"""Independently check that no eval material reached the training corpus.

The notebook already refuses to import a file containing an exact test prompt and
writes its own `eval_separation.json`. This script is a second, independent pass
over the text that was actually trained on (`llm_runs/<run>/corpus.txt`), so the
claim in the README does not rest on the notebook checking itself.

For every run it reports:

* exact prompt hits — a test prompt appearing as a contiguous token sequence,
  both inside a single passage and across the whole corpus file;
* answer-list hits — the four choices of a case appearing in order;
* the longest shared token n-gram between any test prompt and the corpus, which
  is the useful number: it shows how much of a prompt the model could ever have
  seen contiguously, and ordinary language overlap ("the report about the") is
  expected and allowed.

Run:  python scripts/verify_separation.py                 # writes results/separation_check.md
      python scripts/verify_separation.py --print         # also prints the report
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SUITE = ROOT / "evals" / "language_evals.json"


def word_tokens(text: str) -> list[str]:
    return re.findall(r"\w+(?:['’]\w+)*|[^\w\s]", text.lower(), flags=re.UNICODE)


def normalized(text: str) -> str:
    return " " + " ".join(word_tokens(text)) + " "


def ngrams(tokens: list[str], size: int) -> set[tuple[str, ...]]:
    return {tuple(tokens[i:i + size]) for i in range(len(tokens) - size + 1)}


def longest_shared(prompt_tokens: list[str], corpus_ngrams: dict[int, set]) -> int:
    """Longest contiguous run of prompt tokens that also occurs in the corpus."""
    for size in range(len(prompt_tokens), 0, -1):
        table = corpus_ngrams.get(size)
        if table and ngrams(prompt_tokens, size) & table:
            return size
    return 0


def check_run(run_dir: Path, suite: dict) -> dict:
    corpus_text = (run_dir / "corpus.txt").read_text(encoding="utf-8")
    passages = [line for line in corpus_text.splitlines() if line.strip()]
    whole = normalized(corpus_text)
    per_passage = [normalized(p) for p in passages]

    longest_prompt = max(len(word_tokens(c["prompt"])) for c in suite["cases"])
    corpus_ngrams: dict[int, set] = {}
    for passage in passages:
        tokens = word_tokens(passage)
        for size in range(1, min(longest_prompt, len(tokens)) + 1):
            corpus_ngrams.setdefault(size, set()).update(ngrams(tokens, size))

    prompt_hits, answer_hits, overlap = [], [], []
    for case in suite["cases"]:
        prompt = normalized(case["prompt"])
        in_passage = any(prompt in p for p in per_passage)
        in_file = prompt in whole
        if in_passage or in_file:
            prompt_hits.append({"id": case["id"], "in_passage": in_passage, "in_file": in_file})
        if normalized(" ".join(case["choices"])) in whole:
            answer_hits.append(case["id"])
        prompt_tokens = word_tokens(case["prompt"])
        shared = longest_shared(prompt_tokens, corpus_ngrams)
        overlap.append({"id": case["id"], "group": case["group"], "category": case["category"],
                        "prompt_tokens": len(prompt_tokens), "longest_shared_ngram": shared,
                        "fraction": shared / len(prompt_tokens)})

    notebook_check = json.loads((run_dir / "eval_separation.json").read_text(encoding="utf-8"))
    return {"run": run_dir.name, "passages": len(passages), "prompt_hits": prompt_hits,
            "answer_list_hits": answer_hits, "overlap": overlap,
            "notebook_eval_separation": notebook_check}


def render(reports: list[dict], suite: dict) -> str:
    lines = ["# Corpus / eval separation check", "",
             "Generated by `scripts/verify_separation.py`. This is an independent pass over the",
             "text each run actually trained on (`corpus.txt`), separate from the notebook's own",
             f"`eval_separation.json`. Suite: `{suite['suite_id']}`, {len(suite['cases'])} cases.", ""]
    lines += ["| run | passages | exact prompt hits | answer-list hits | notebook-reserved passages | max shared n-gram |",
              "| --- | --- | --- | --- | --- | --- |"]
    for report in reports:
        worst = max(report["overlap"], key=lambda row: row["longest_shared_ngram"])
        lines.append(f"| `{report['run']}` | {report['passages']:,} | "
                     f"**{len(report['prompt_hits'])}** | **{len(report['answer_list_hits'])}** | "
                     f"{report['notebook_eval_separation']['excluded_passages']} | "
                     f"{worst['longest_shared_ngram']} tokens ({worst['id']}) |")
    lines.append("")
    for report in reports:
        lines += [f"## `{report['run']}`", ""]
        if report["prompt_hits"]:
            lines.append(f"**FAIL — test prompts found in training text:** {report['prompt_hits']}")
        else:
            lines.append("No test prompt appears in any training passage, or in the whole corpus file.")
        if report["answer_list_hits"]:
            lines.append(f"**FAIL — answer lists found:** {report['answer_list_hits']}")
        else:
            lines.append("No case's four answer choices appear in order anywhere in the corpus.")
        lines += ["", "Longest contiguous token overlap between each test prompt and the corpus "
                      "(ordinary shared language is expected; the point is that no prompt is "
                      "reproduced in full):", "",
                  "| case | category | prompt tokens | longest shared run | fraction |",
                  "| --- | --- | --- | --- | --- |"]
        for row in sorted(report["overlap"], key=lambda r: -r["fraction"])[:10]:
            lines.append(f"| {row['id']} | {row['category']} | {row['prompt_tokens']} | "
                         f"{row['longest_shared_ngram']} | {row['fraction']:.0%} |")
        lines += ["", f"(top 10 of {len(report['overlap'])} cases by overlap fraction; "
                      "the full table is in `results/separation_check.json`)", ""]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", nargs="*", type=Path,
                        help="run folders (default: every folder under llm_runs/)")
    parser.add_argument("--out", type=Path, default=ROOT / "results")
    parser.add_argument("--print", dest="show", action="store_true")
    args = parser.parse_args()

    suite = json.loads(SUITE.read_text(encoding="utf-8"))
    runs = args.runs or sorted(p for p in (ROOT / "llm_runs").iterdir() if p.is_dir())
    reports = [check_run(run, suite) for run in runs]

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "separation_check.json").write_text(
        json.dumps(reports, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    report_text = render(reports, suite)
    (args.out / "separation_check.md").write_text(report_text, encoding="utf-8")
    if args.show:
        print(report_text)

    failures = sum(len(r["prompt_hits"]) + len(r["answer_list_hits"]) for r in reports)
    for report in reports:
        status = "FAIL" if report["prompt_hits"] or report["answer_list_hits"] else "clean"
        print(f"{report['run']}: {status} "
              f"({report['passages']:,} passages, {len(report['prompt_hits'])} prompt hits, "
              f"{len(report['answer_list_hits'])} answer-list hits)")
    print(f"wrote {args.out/'separation_check.md'}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
